Add a hook for ``toga``, which has metadata
Failing with:

Traceback (most recent call last):
  File "toga/icons.py", line 33, in __get__
AttributeError: type object 'Icon' has no attribute '__APP_ICON'. Did you mean: 'APP_ICON'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "toga/icons.py", line 126, in __init__
  File "toga/icons.py", line 183, in _full_path
FileNotFoundError: Can't find icon resources/gotcha

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_source.py", line 8, in <module>
  File "toga/app.py", line 314, in __init__
  File "toga/icons.py", line 35, in __get__
  File "toga/icons.py", line 68, in APP_ICON
  File "toga/icons.py", line 141, in __init__
  File "toga_cocoa/icons.py", line 21, in __init__
  File "pathlib.py", line 1162, in __init__
  File "pathlib.py", line 373, in __init__
TypeError: argument should be a str or an os.PathLike object where __fspath__ returns a str, not 'NoneType'