hooks: add hook for setuptools_scm
Add hook for `setuptools_scm` to ensure that metadata for `setuptools`
dist is collected, in order to avoid the following run-time warning:

```
ERROR: setuptools==0.dev0+unknown is used in combination with setuptools_scm>=8.x

Your build configuration is incomplete and previously worked by accident!
setuptools_scm requires setuptools>=61

Suggested workaround if applicable:
 - migrating from the deprecated setup_requires mechanism to pep517/518
   and using a pyproject.toml to declare build dependencies
   which are reliably pre-installed before running the build tools
```